import { DIFFICULTIES } from '../react/constants';

export const CULL_COUNT = {
  [DIFFICULTIES.EASY]: 42,
  [DIFFICULTIES.MEDIUM]: 50,
  [DIFFICULTIES.HARD]: 58,
  [DIFFICULTIES.EXPERT]: 66
};

export const GIVEN_COUNT = {
  [DIFFICULTIES.EASY]: 60,
  [DIFFICULTIES.MEDIUM]: 56,
  [DIFFICULTIES.HARD]: 50,
  //[DIFFICULTIES.EXPERT]: 35
  [DIFFICULTIES.EXPERT]: 80
};
