import { DIFFICULTIES } from '../react/constants';

export const CULL_COUNT = {
  [DIFFICULTIES.EASY]: 42,
  [DIFFICULTIES.MEDIUM]: 50,
  [DIFFICULTIES.HARD]: 58,
  [DIFFICULTIES.EXPERT]: 66
};

export const GIVEN_COUNT = {
  [DIFFICULTIES.EASY]: 62,
  [DIFFICULTIES.MEDIUM]: 53,
  [DIFFICULTIES.HARD]: 44,
  [DIFFICULTIES.EXPERT]: 35
};
